import type { WorkIssue, WorkProject, WorkStep } from "./work-board.types";

export const STEPS: WorkStep[] = [
  { id: "intake", name: "Tiếp nhận", macro: "Intake" },
  { id: "drafting", name: "Soạn thảo", macro: "In Progress" },
  { id: "customer", name: "Chờ khách hàng", macro: "External" },
  { id: "signing", name: "Ký kết", macro: "Approval" },
  { id: "billing", name: "Thanh toán", macro: "Billing" },
  { id: "done", name: "Hoàn tất", macro: "Archived" },
  { id: "unassigned", name: "Unassigned", macro: "Unassigned" },
];

export const PROJECTS: WorkProject[] = [
  { id: "prj-1024", name: "M&A Delta", customer: "Delta Holdings" },
  { id: "prj-1038", name: "KCN Tân Việt", customer: "KCN Tân Việt" },
  { id: "prj-1044", name: "Hợp đồng Đông Phú", customer: "Đông Phú Logistics" },
];

export const INITIAL_ISSUES: WorkIssue[] = [
  {
    id: "ISS-2418",
    title: "Kiểm tra hồ sơ pháp lý bên bán trước phiên ký",
    projectId: "prj-1024",
    step: "intake",
    status: "TODO",
    assignee: "Lan",
    due: "2026-06-16",
    labels: ["contract", "urgent"],
    description: "Đối chiếu checklist hồ sơ pháp lý trước khi chuyển sang drafting.",
    created: "2026-06-12",
    updated: "09:20",
    priority: "HIGH",
  },
  {
    id: "ISS-2419",
    title: "Soạn phụ lục điều chỉnh điều khoản thanh toán",
    projectId: "prj-1044",
    step: "drafting",
    status: "DOING",
    assignee: "Minh",
    due: "2026-06-18",
    labels: ["billing"],
    description: "Chuẩn bị bản nháp phụ lục B theo yêu cầu kế toán.",
    created: "2026-06-13",
    updated: "08:45",
    priority: "MEDIUM",
  },
  {
    id: "ISS-2420",
    title: "Chờ khách hàng xác nhận danh sách người ký",
    projectId: "prj-1038",
    step: "customer",
    status: "DOING",
    assignee: "Huy",
    due: "2026-06-15",
    labels: ["customer"],
    description: "Cần xác nhận thẩm quyền ký trước khi phát hành bản cuối.",
    created: "2026-06-10",
    updated: "Hôm qua",
    priority: "HIGH",
  },
  {
    id: "ISS-2421",
    title: "Rà soát điều khoản bảo mật cho hồ sơ lao động",
    projectId: "prj-1038",
    step: "drafting",
    status: "TODO",
    assignee: "Lan",
    due: "2026-06-21",
    labels: ["contract"],
    description: "Đảm bảo điều khoản bảo mật khớp mẫu mới.",
    created: "2026-06-14",
    updated: "10:05",
    priority: "LOW",
  },
  {
    id: "ISS-2422",
    title: "Chuẩn bị bộ ký điện tử cho hợp đồng dịch vụ",
    projectId: "prj-1044",
    step: "signing",
    status: "DOING",
    assignee: "Minh",
    due: "2026-06-17",
    labels: ["contract"],
    description: "Upload bản cuối và kiểm tra thứ tự ký.",
    created: "2026-06-11",
    updated: "11:10",
    priority: "MEDIUM",
  },
  {
    id: "ISS-2423",
    title: "Xác nhận invoice sau nghiệm thu đợt 2",
    projectId: "prj-1044",
    step: "billing",
    status: "TODO",
    assignee: "Unassigned",
    due: "2026-06-16",
    labels: ["billing", "urgent"],
    description: "Chưa có người phụ trách. Cần assign trước cuối ngày.",
    created: "2026-06-15",
    updated: "12:30",
    priority: "URGENT",
  },
  {
    id: "ISS-2424",
    title: "Đóng checklist lưu trữ hồ sơ sau ký",
    projectId: "prj-1024",
    step: "done",
    status: "DONE",
    assignee: "Huy",
    due: "2026-06-14",
    labels: ["contract"],
    description: "Hoàn tất lưu trữ và cập nhật activity log.",
    created: "2026-06-09",
    updated: "Thứ sáu",
    priority: "LOW",
  },
  {
    id: "ISS-2425",
    title: "Thiếu workflow step từ API trả về",
    projectId: "prj-1038",
    step: "unassigned",
    status: "TODO",
    assignee: "Unassigned",
    due: "2026-06-20",
    labels: ["customer"],
    description: "Issue nằm trong unassigned_tasks cho đến khi chọn workflow step.",
    created: "2026-06-15",
    updated: "13:05",
    priority: "MEDIUM",
  },
];

export const TODAY = new Date("2026-06-16T00:00:00");
