"use client";

import { Alert, Button, Card, Empty, Form, Input, InputNumber, Select, Space, Table, Tag, Typography } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { createTimeEntry, deleteTimeEntry, listTimeEntries, type CreateTimeEntryRequest, type TimeEntry } from "@/api/time-entries.api";
import { getUserFacingErrorMessage } from "@/api/errors";

export function TimeEntriesPage() {
  const client = useQueryClient();
  const [projectId, setProjectId] = useState("");
  const [activeProjectId, setActiveProjectId] = useState("");
  const entries = useQuery({ queryKey: ["time-entries", activeProjectId], queryFn: ({ signal }) => listTimeEntries({ project_id: activeProjectId, limit: 50 }, signal), enabled: Boolean(activeProjectId) });
  const create = useMutation({ mutationFn: (values: CreateTimeEntryRequest) => createTimeEntry({ ...values, project_id: activeProjectId }), onSuccess: () => client.invalidateQueries({ queryKey: ["time-entries", activeProjectId] }) });
  const remove = useMutation({ mutationFn: deleteTimeEntry, onSuccess: () => client.invalidateQueries({ queryKey: ["time-entries", activeProjectId] }) });
  return <section className="workflow-page" aria-labelledby="time-entries-title"><header className="workflow-page__header"><div><Typography.Title id="time-entries-title" level={2}>Time Entries</Typography.Title><Typography.Text type="secondary">Ghi nhận thời gian và trạng thái billing của project.</Typography.Text></div></header><Card><Space.Compact style={{ width: "100%" }}><Input value={projectId} onChange={(event) => setProjectId(event.target.value)} placeholder="Nhập project ID" onPressEnter={() => setActiveProjectId(projectId.trim())} /><Button type="primary" onClick={() => setActiveProjectId(projectId.trim())}>Tải danh sách</Button></Space.Compact></Card>{activeProjectId ? <><Card title="Ghi nhận thời gian"><Form layout="inline" onFinish={(values) => create.mutate(values as CreateTimeEntryRequest)}><Form.Item name="duration_minutes" rules={[{ required: true, message: "Nhập số phút" }]}><InputNumber min={1} placeholder="Số phút" /></Form.Item><Form.Item name="description" rules={[{ required: true, message: "Nhập mô tả" }]}><Input placeholder="Mô tả công việc" /></Form.Item><Form.Item name="billable" initialValue={true}><Select options={[{ value: true, label: "Billable" }, { value: false, label: "Non-billable" }]} style={{ width: 140 }} /></Form.Item><Button htmlType="submit" type="primary" loading={create.isPending}>Thêm</Button></Form></Card>{create.isError || entries.isError ? <Alert type="error" message={getUserFacingErrorMessage(create.error ?? entries.error)} /> : entries.data?.data.length === 0 && !entries.isPending ? <Card><Empty description="Chưa có time entry" /></Card> : <Card><Table<TimeEntry> rowKey="id" loading={entries.isPending || entries.isFetching} dataSource={entries.data?.data ?? []} pagination={false} columns={[{ title: "Mô tả", dataIndex: "description" }, { title: "Thời lượng", render: (_, entry) => `${entry.duration_minutes || entry.minutes || 0} phút` }, { title: "Billing", render: (_, entry) => <Tag color={entry.billable ? "blue" : "default"}>{entry.billable ? "Billable" : "Non-billable"}</Tag> }, { title: "Invoice", render: (_, entry) => entry.invoice_id ? <Tag color="green">Đã invoice</Tag> : "Chưa invoice" }, { title: "Thao tác", render: (_, entry) => !entry.invoice_id && entry.actions?.delete !== false ? <Button danger type="link" loading={remove.isPending && remove.variables === entry.id} onClick={() => remove.mutate(entry.id)}>Xóa</Button> : null }]} /></Card>}</> : <Card><Empty description="Nhập project ID để bắt đầu" /></Card>}</section>;
}
