"use client";

import Link from "next/link";
import { Alert, Button, Card, Descriptions, Empty, Input, Modal, Skeleton, Space, Table, Tag, Typography } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { closeProject, getProject, overrideProjectConflict } from "@/api/projects.api";
import { listProjectPayments, type ProjectPayment } from "@/api/project-payments.api";
import { getUserFacingErrorMessage } from "@/api/errors";
import { DocumentsPage } from "@/features/documents";

export function ProjectDetailPage({ projectId }: { projectId: string }) {
  const client = useQueryClient(); const [overrideOpen, setOverrideOpen] = useState(false); const [justification, setJustification] = useState("");
  const query = useQuery({ queryKey: ["project", projectId], queryFn: ({ signal }) => getProject(projectId, signal) });
  const payments = useQuery({ queryKey: ["project", projectId, "payments"], queryFn: ({ signal }) => listProjectPayments({ project_id: projectId }, signal), enabled: query.isSuccess });
  const close = useMutation({ mutationFn: () => closeProject(projectId), onSuccess: () => client.invalidateQueries({ queryKey: ["project", projectId] }) });
  const override = useMutation({ mutationFn: () => overrideProjectConflict(projectId, { override_justification: justification.trim() }), onSuccess: async () => { setOverrideOpen(false); setJustification(""); await client.invalidateQueries({ queryKey: ["project", projectId] }); } });
  if (query.isPending) return <Card><Skeleton active paragraph={{ rows: 10 }} /></Card>;
  if (query.isError) return <Alert type="error" message={getUserFacingErrorMessage(query.error)} action={<Button onClick={() => query.refetch()}>Thử lại</Button>} />;
  const project = query.data;
  return <section className="workflow-page"><header className="workflow-page__header"><div><Link href="/projects">← Projects</Link><Typography.Title level={2}>{project.name}</Typography.Title><Typography.Text type="secondary">{project.customer_name || project.customer_id}</Typography.Text></div><Space>{project.status === "ACTIVE" ? <Button danger onClick={() => close.mutate()} loading={close.isPending}>Đóng project</Button> : <Tag>Đã đóng</Tag>}{project.conflict_status === "CONFLICT_DETECTED" ? <Button onClick={() => setOverrideOpen(true)}>Override conflict</Button> : null}</Space></header><Card><Descriptions bordered column={{ xs: 1, sm: 2 }}><Descriptions.Item label="Status">{project.status}</Descriptions.Item><Descriptions.Item label="Workflow">{project.current_workflow_step_name || "—"}</Descriptions.Item><Descriptions.Item label="Conflict"><Tag color={project.conflict_status === "CONFLICT_DETECTED" ? "error" : "success"}>{project.conflict_status}</Tag></Descriptions.Item><Descriptions.Item label="Hourly rate">{project.hourly_rate.toLocaleString("vi-VN")} ₫</Descriptions.Item><Descriptions.Item label="Giá trị hợp đồng">{project.total_contract_value.toLocaleString("vi-VN")} ₫</Descriptions.Item><Descriptions.Item label="Đã thu">{project.total_paid.toLocaleString("vi-VN")} ₫</Descriptions.Item><Descriptions.Item label="Còn lại">{project.remaining_amount.toLocaleString("vi-VN")} ₫</Descriptions.Item><Descriptions.Item label="Bên đối lập">{project.opposing_party_name || "—"}</Descriptions.Item></Descriptions></Card><Card title="Payments">{payments.isError ? <Alert type="error" message={getUserFacingErrorMessage(payments.error)} action={<Button onClick={() => payments.refetch()}>Thử lại</Button>} /> : <Table<ProjectPayment> rowKey="id" loading={payments.isPending} dataSource={payments.data?.data ?? []} pagination={false} locale={{ emptyText: <Empty description="Chưa có payment" /> }} columns={[{ title: "Ngày", dataIndex: "paid_at", render: (value: string) => new Date(value).toLocaleString("vi-VN") }, { title: "Số tiền", dataIndex: "amount", render: (value: number) => `${value.toLocaleString("vi-VN")} ₫` }, { title: "Loại", dataIndex: "payment_type" }, { title: "Phương thức", dataIndex: "payment_method", render: (value) => value || "—" }, { title: "Ghi chú", dataIndex: "note", render: (value) => value || "—" }]} />}</Card><Card title="Tài liệu dự án"><DocumentsPage initialProjectId={project.id} /></Card><Modal open={overrideOpen} title="Override conflict" okText="Xác nhận" cancelText="Hủy" confirmLoading={override.isPending} okButtonProps={{ disabled: justification.trim().length < 50 }} onCancel={() => setOverrideOpen(false)} onOk={() => override.mutate()}><Input.TextArea rows={5} value={justification} onChange={(event) => setJustification(event.target.value)} placeholder="Lý do tối thiểu 50 ký tự" /></Modal></section>;
}
