import { STEPS } from "../model/work-board.fixtures";
import type { ViewMode, WorkIssue, WorkStepId } from "../model/work-board.types";
import { dueState, projectFor, stepFor } from "../model/work-board.utils";
import { IssueCard } from "./IssueCard";
import { StatusChip } from "./WorkBoardPrimitives";

export function WorkBoardViews({ viewMode, issues, selectedIssueId, readonly, activeStep, dropTarget, onDropTargetChange, onMoveIssue, onOpenIssue, onReadonlyDrag, onClearFilters }: { viewMode: ViewMode; issues: WorkIssue[]; selectedIssueId: string | null; readonly: boolean; activeStep: WorkStepId; dropTarget: WorkStepId | null; onDropTargetChange: (step: WorkStepId | null) => void; onMoveIssue: (issueId: string, step: WorkStepId) => void; onOpenIssue: (issueId: string) => void; onReadonlyDrag: () => void; onClearFilters: () => void }) {
  return <div className="od-workboard__board-wrap">{viewMode === "board" ? <div className="od-workboard__board-scroll"><div className="od-workboard__board">{STEPS.map((step) => {
    const columnIssues = issues.filter((issue) => issue.step === step.id);
    return <section key={step.id} className={`od-workboard__column ${dropTarget === step.id ? "is-drop-target" : ""} ${step.id === activeStep ? "is-mobile-active" : ""}`} aria-label={step.name} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; onDropTargetChange(step.id); }} onDragEnter={() => onDropTargetChange(step.id)} onDragLeave={() => onDropTargetChange(null)} onDrop={(event) => { event.preventDefault(); onDropTargetChange(null); onMoveIssue(event.dataTransfer.getData("text/plain"), step.id); }}><header className="od-workboard__column-head"><div className="od-workboard__column-title"><strong>{step.name}</strong><span>{step.macro}</span></div><span className="od-workboard__count-badge">{columnIssues.length}</span></header><div className="od-workboard__card-list">{columnIssues.length > 0 ? columnIssues.map((issue) => <IssueCard key={issue.id} issue={issue} selected={selectedIssueId === issue.id} readonly={readonly} onOpen={() => onOpenIssue(issue.id)} onDragStart={() => { if (readonly) { onReadonlyDrag(); return false; } return true; }} onDragEnd={() => onDropTargetChange(null)} />) : <div className="od-workboard__empty-column">Không có issue</div>}</div></section>;
  })}</div></div> : null}{viewMode === "list" ? <div className="od-workboard__list-view"><table><thead><tr><th>Title</th><th>Project</th><th>Workflow step</th><th>Status</th><th>Assignee</th><th>Due date</th><th>Labels</th><th>Updated at</th><th>Actions</th></tr></thead><tbody>{issues.length > 0 ? issues.map((issue) => { const project = projectFor(issue); return <tr key={issue.id}><td><strong>{issue.title}</strong><span>{issue.id}</span></td><td><a href={`/projects/${issue.projectId}`}>{project.name}</a><span>{project.customer}</span></td><td>{stepFor(issue.step).name}</td><td><StatusChip status={issue.status} /></td><td>{issue.assignee}</td><td><span className={`od-workboard__due ${dueState(issue.due)}`}>{issue.due}</span></td><td><div className="od-workboard__chip-row">{issue.labels.map((label) => <span key={label} className="od-workboard__chip">{label}</span>)}</div></td><td>{issue.updated}</td><td><button className="od-workboard__button" type="button" onClick={() => onOpenIssue(issue.id)}>Open</button></td></tr>; }) : <tr><td colSpan={9}><strong>Chưa có issue trong bộ lọc hiện tại.</strong>{" "}<button className="od-workboard__button" type="button" onClick={onClearFilters}>Clear filters</button></td></tr>}</tbody></table></div> : null}</div>;
}
