"use client";

import { Alert, Button, Card, Empty, Form, Input, Select, Space, Table, Tag, Typography } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { generateInvoice, listInvoices, updateInvoiceStatus, type GenerateInvoiceRequest, type Invoice, type InvoiceStatus, INVOICE_STATUSES } from "@/api/invoices.api";
import { getUserFacingErrorMessage } from "@/api/errors";

export function InvoicesPage() {
  const client = useQueryClient();
  const [customerId, setCustomerId] = useState("");
  const [activeCustomerId, setActiveCustomerId] = useState("");
  const [status, setStatus] = useState<InvoiceStatus | undefined>();
  const invoices = useQuery({ queryKey: ["invoices", activeCustomerId, status], queryFn: ({ signal }) => listInvoices({ customer_id: activeCustomerId, status }, signal), enabled: Boolean(activeCustomerId) });
  const generate = useMutation({ mutationFn: (values: GenerateInvoiceRequest) => generateInvoice({ ...values, customer_id: activeCustomerId }), onSuccess: () => client.invalidateQueries({ queryKey: ["invoices", activeCustomerId] }) });
  const changeStatus = useMutation({ mutationFn: ({ id, nextStatus }: { id: string; nextStatus: InvoiceStatus }) => updateInvoiceStatus(id, { status: nextStatus }), onSuccess: () => client.invalidateQueries({ queryKey: ["invoices", activeCustomerId] }) });
  return <section className="workflow-page" aria-labelledby="invoices-title"><header className="workflow-page__header"><div><Typography.Title id="invoices-title" level={2}>Invoices</Typography.Title><Typography.Text type="secondary">Theo dõi invoice và chuyển trạng thái billing.</Typography.Text></div></header><Card><Space.Compact style={{ width: "100%" }}><Input value={customerId} onChange={(event) => setCustomerId(event.target.value)} placeholder="Nhập customer ID" onPressEnter={() => setActiveCustomerId(customerId.trim())} /><Select allowClear placeholder="Mọi trạng thái" value={status} onChange={(value) => setStatus(value)} options={INVOICE_STATUSES.map((value) => ({ value, label: value }))} style={{ width: 150 }} /><Button type="primary" onClick={() => setActiveCustomerId(customerId.trim())}>Tải danh sách</Button></Space.Compact></Card>{activeCustomerId ? <><Card title="Tạo invoice"><Form layout="inline" onFinish={(values) => generate.mutate(values as GenerateInvoiceRequest)}><Form.Item name="project_id" rules={[{ required: true, message: "Nhập project ID" }]}><Input placeholder="Project ID" /></Form.Item><Form.Item name="status" initialValue="DRAFT"><Select options={INVOICE_STATUSES.map((value) => ({ value, label: value }))} style={{ width: 130 }} /></Form.Item><Button htmlType="submit" type="primary" loading={generate.isPending}>Tạo</Button></Form></Card>{generate.isError || invoices.isError ? <Alert type="error" message={getUserFacingErrorMessage(generate.error ?? invoices.error)} /> : invoices.data?.data.length === 0 && !invoices.isPending ? <Card><Empty description="Chưa có invoice" /></Card> : <Card><Table<Invoice> rowKey="id" loading={invoices.isPending || invoices.isFetching} dataSource={invoices.data?.data ?? []} pagination={false} columns={[{ title: "Invoice", dataIndex: "id", render: (id: string) => <Typography.Text copyable={{ text: id }}>{id.slice(0, 12)}…</Typography.Text> }, { title: "Tổng tiền", dataIndex: "total_amount", render: (value: number) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value) }, { title: "Trạng thái", dataIndex: "status", render: (value: InvoiceStatus) => <Tag color={value === "PAID" ? "success" : value === "VOID" ? "default" : "warning"}>{value}</Tag> }, { title: "Cập nhật", render: (_, invoice) => invoice.status !== "PAID" && invoice.status !== "VOID" ? <Space><Button size="small" onClick={() => changeStatus.mutate({ id: invoice.id, nextStatus: "PAID" })}>Đã thanh toán</Button><Button size="small" danger onClick={() => changeStatus.mutate({ id: invoice.id, nextStatus: "VOID" })}>Void</Button></Space> : null }]} /></Card>}</> : <Card><Empty description="Nhập customer ID để bắt đầu" /></Card>}</section>;
}
