"use client";
import Link from "next/link";
import { Alert, Button, Card, Descriptions, Empty, Skeleton, Space, Table, Tag, Typography } from "antd";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getInvoice, listInvoiceTimeEntries, updateInvoiceStatus, type InvoiceStatus } from "@/api/invoices.api";
import { getUserFacingErrorMessage } from "@/api/errors";
export function InvoiceDetailPage({ invoiceId }: { invoiceId: string }) {
  const client = useQueryClient(); const invoice = useQuery({ queryKey: ["invoice", invoiceId], queryFn: ({ signal }) => getInvoice(invoiceId, signal) }); const entries = useQuery({ queryKey: ["invoice", invoiceId, "entries"], queryFn: ({ signal }) => listInvoiceTimeEntries(invoiceId, signal), enabled: invoice.isSuccess });
  const status = useMutation({ mutationFn: (nextStatus: InvoiceStatus) => updateInvoiceStatus(invoiceId, { status: nextStatus }), onSuccess: () => client.invalidateQueries({ queryKey: ["invoice", invoiceId] }) });
  if (invoice.isPending) return <Card><Skeleton active paragraph={{ rows: 8 }} /></Card>; if (invoice.isError) return <Alert type="error" message={getUserFacingErrorMessage(invoice.error)} action={<Button onClick={() => invoice.refetch()}>Thử lại</Button>} />; const data = invoice.data;
  return <section className="workflow-page"><Link href="/invoices">← Invoices</Link><header className="workflow-page__header"><div><Typography.Title level={2}>Invoice {data.id.slice(0, 12)}…</Typography.Title><Typography.Text type="secondary">Customer: {data.customer_id}</Typography.Text></div><Space><Tag color={data.status === "PAID" ? "success" : data.status === "VOID" ? "default" : "warning"}>{data.status}</Tag>{data.status !== "PAID" && data.status !== "VOID" ? <><Button onClick={() => status.mutate("PAID")} loading={status.isPending}>Đã thanh toán</Button><Button danger onClick={() => status.mutate("VOID")} loading={status.isPending}>Void</Button></> : null}</Space></header><Card><Descriptions bordered column={2}><Descriptions.Item label="Tổng tiền">{data.total_amount.toLocaleString("vi-VN")} ₫</Descriptions.Item><Descriptions.Item label="Ngày phát hành">{new Date(data.issued_at).toLocaleString("vi-VN")}</Descriptions.Item><Descriptions.Item label="Tạo lúc">{new Date(data.created_at).toLocaleString("vi-VN")}</Descriptions.Item></Descriptions></Card><Card title="Time entries"><Table rowKey="id" loading={entries.isPending} dataSource={entries.data?.data ?? []} pagination={false} locale={{ emptyText: <Empty description="Chưa có time entry" /> }} columns={[{ title: "Mô tả", dataIndex: "description" }, { title: "Phút", dataIndex: "duration_minutes" }, { title: "Billable", render: (_, row) => row.billable ? <Tag color="blue">Có</Tag> : "Không" }]} /></Card></section>;
}
